version: "3.1"

services:
  db:
    container_name: database
    image: postgres:14
    environment:
     - POSTGRES_USER=$DB_USER
     - POSTGRES_PASSWORD=$DB_PASS
     - POSTGRES_DB=$DB_DATABASE
    restart: always
    ports:
      - 8050:8050
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python3 main.py
    restart: always
    volumes:
    - .:/src
    networks:
    - botnet
    env_file:
          - ".env"

    depends_on:
      - db

networks:
  botnet:
    driver: bridge